name: aqary_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
